import { DiagramPage, ShapeCategory } from '../types/diagram';

export interface TemplateDefinition {
  id: string;
  name: string;
  category: ShapeCategory | 'academic' | 'infrastructure';
  description: string;
  figureCaption: string;
  figureNumber: string;
  preset: 'A4' | 'A3' | 'Letter';
  orientation: 'landscape' | 'portrait';
  page: DiagramPage;
}

export const TEMPLATE_CATALOG: TemplateDefinition[] = [
  // 1. Full-Stack Web Application Architecture
  {
    id: 'web-app-architecture',
    name: 'Full-Stack Web App Architecture',
    category: 'software',
    description: 'Modern 3-tier web architecture with CDN, reverse proxy, API backend, cache, and database.',
    figureNumber: 'Figure 3.1',
    figureCaption: 'Production Multi-Tier Web Application Architecture',
    preset: 'A4',
    orientation: 'landscape',
    page: {
      id: 'page-web-app',
      name: 'System Architecture',
      preset: 'A4',
      orientation: 'landscape',
      width: 1123,
      height: 794,
      background: '#ffffff',
      gridEnabled: true,
      gridSize: 20,
      snapToGrid: true,
      figureNumber: 'Figure 3.1',
      figureCaption: 'Production Multi-Tier Web Application Architecture',
      captionPosition: 'below',
      nodes: [
        {
          id: 'node-user',
          type: 'soft-user',
          category: 'software',
          label: 'Client User',
          subLabel: 'HTTPS Browser / Mobile',
          x: 60,
          y: 280,
          width: 110,
          height: 90,
          fill: '#f8fafc',
          stroke: '#334155',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 1,
        },
        {
          id: 'node-cdn',
          type: 'soft-browser',
          category: 'software',
          label: 'CloudFront CDN',
          subLabel: 'Static SPA Assets & WAF',
          x: 230,
          y: 280,
          width: 150,
          height: 90,
          fill: '#ffffff',
          stroke: '#0284c7',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 2,
        },
        {
          id: 'node-lb',
          type: 'soft-load-balancer',
          category: 'software',
          label: 'Nginx Ingress / ALB',
          subLabel: 'SSL Termination & Balancing',
          x: 430,
          y: 280,
          width: 160,
          height: 85,
          fill: '#ffffff',
          stroke: '#0d9488',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 3,
        },
        {
          id: 'node-auth',
          type: 'soft-auth',
          category: 'software',
          label: 'Auth Service',
          subLabel: 'OAuth2 & JWT Verification',
          x: 640,
          y: 120,
          width: 160,
          height: 80,
          fill: '#ffffff',
          stroke: '#e11d48',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 4,
        },
        {
          id: 'node-api',
          type: 'soft-backend',
          category: 'software',
          label: 'Node.js REST API',
          subLabel: 'Express & Business Logic',
          x: 640,
          y: 280,
          width: 160,
          height: 85,
          fill: '#ffffff',
          stroke: '#16a34a',
          strokeWidth: 2,
          strokeStyle: 'solid',
          is3D: true,
          depth3D: 10,
          zIndex: 5,
        },
        {
          id: 'node-cache',
          type: 'soft-cache',
          category: 'software',
          label: 'Redis Cache',
          subLabel: 'Session Store & Rate Limit',
          x: 640,
          y: 440,
          width: 160,
          height: 80,
          fill: '#ffffff',
          stroke: '#dc2626',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 6,
        },
        {
          id: 'node-db',
          type: '3d-cylinder',
          category: 'technical-3d',
          label: 'PostgreSQL DB',
          subLabel: 'ACID Primary Database',
          x: 880,
          y: 260,
          width: 140,
          height: 110,
          fill: '#f0f9ff',
          stroke: '#0284c7',
          strokeWidth: 2,
          strokeStyle: 'solid',
          is3D: true,
          depth3D: 14,
          zIndex: 7,
        },
        {
          id: 'node-s3',
          type: 'soft-storage',
          category: 'software',
          label: 'AWS S3 Bucket',
          subLabel: 'Media & Document Storage',
          x: 880,
          y: 440,
          width: 140,
          height: 85,
          fill: '#ffffff',
          stroke: '#059669',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 8,
        },
      ],
      edges: [
        {
          id: 'edge-1',
          source: 'node-user',
          target: 'node-cdn',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'HTTPS :443',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#334155',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'edge-2',
          source: 'node-cdn',
          target: 'node-lb',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'API Request',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#0284c7',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'edge-3',
          source: 'node-lb',
          target: 'node-api',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Proxy Route',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#0d9488',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'edge-4',
          source: 'node-api',
          target: 'node-auth',
          sourceHandle: 'top',
          targetHandle: 'bottom',
          label: 'Verify Token',
          lineType: 'orthogonal',
          arrowType: 'double-arrow',
          stroke: '#e11d48',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'edge-5',
          source: 'node-api',
          target: 'node-cache',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          label: 'Cache Read / Write',
          lineType: 'orthogonal',
          arrowType: 'double-arrow',
          stroke: '#dc2626',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'edge-6',
          source: 'node-api',
          target: 'node-db',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Prisma / SQL',
          lineType: 'orthogonal',
          arrowType: 'double-arrow',
          stroke: '#0284c7',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'edge-7',
          source: 'node-api',
          target: 'node-s3',
          sourceHandle: 'bottom',
          targetHandle: 'left',
          label: 'Presigned URL',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#059669',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
      ],
    },
  },

  // 2. Final Year Project: College Event Management Flowchart
  {
    id: 'college-event-flowchart',
    name: 'Event Registration & Attendance Flow',
    category: 'flowchart',
    description: 'Standard academic flowchart for student event registration, QR ticket generation, and verification.',
    figureNumber: 'Figure 4.2',
    figureCaption: 'Flowchart of the Event Ticketing and Attendance Verification Subsystem',
    preset: 'A4',
    orientation: 'portrait',
    page: {
      id: 'page-flow-event',
      name: 'Event Attendance Flowchart',
      preset: 'A4',
      orientation: 'portrait',
      width: 794,
      height: 1123,
      background: '#ffffff',
      gridEnabled: true,
      gridSize: 20,
      snapToGrid: true,
      figureNumber: 'Figure 4.2',
      figureCaption: 'Flowchart of the Event Ticketing and Attendance Verification Subsystem',
      captionPosition: 'below',
      nodes: [
        {
          id: 'flow-start',
          type: 'flow-start-end',
          category: 'flowchart',
          label: 'Student Opens Portal',
          x: 320,
          y: 40,
          width: 160,
          height: 50,
          fill: '#f1f5f9',
          stroke: '#0f172a',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 1,
        },
        {
          id: 'flow-login',
          type: 'flow-process',
          category: 'flowchart',
          label: 'Authenticate Student ID',
          subLabel: 'SSO / LDAP Credential Check',
          x: 310,
          y: 130,
          width: 180,
          height: 65,
          fill: '#ffffff',
          stroke: '#0284c7',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 2,
        },
        {
          id: 'flow-check-auth',
          type: 'flow-decision',
          category: 'flowchart',
          label: 'Credentials Valid?',
          x: 330,
          y: 235,
          width: 140,
          height: 90,
          fill: '#ffffff',
          stroke: '#d97706',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 3,
        },
        {
          id: 'flow-select-event',
          type: 'flow-process',
          category: 'flowchart',
          label: 'Select Target Event',
          subLabel: 'Browse Available Slots',
          x: 310,
          y: 370,
          width: 180,
          height: 65,
          fill: '#ffffff',
          stroke: '#0284c7',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 4,
        },
        {
          id: 'flow-seats-available',
          type: 'flow-decision',
          category: 'flowchart',
          label: 'Seats Available?',
          x: 330,
          y: 480,
          width: 140,
          height: 90,
          fill: '#ffffff',
          stroke: '#d97706',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 5,
        },
        {
          id: 'flow-gen-qr',
          type: 'flow-process',
          category: 'flowchart',
          label: 'Generate Cryptographic QR',
          subLabel: 'HMAC-SHA256 Signed Payload',
          x: 300,
          y: 620,
          width: 200,
          height: 70,
          fill: '#f0fdf4',
          stroke: '#16a34a',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 6,
        },
        {
          id: 'flow-scan-qr',
          type: 'flow-input-output',
          category: 'flowchart',
          label: 'Organizer Scans QR at Venue',
          subLabel: 'Handheld Mobile Scanner',
          x: 300,
          y: 730,
          width: 200,
          height: 65,
          fill: '#ffffff',
          stroke: '#0369a1',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 7,
        },
        {
          id: 'flow-record-db',
          type: 'flow-database',
          category: 'flowchart',
          label: 'Record Attendance DB',
          subLabel: 'Audit Log & Timestamp',
          x: 325,
          y: 840,
          width: 150,
          height: 85,
          fill: '#ffffff',
          stroke: '#0284c7',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 8,
        },
        {
          id: 'flow-end',
          type: 'flow-start-end',
          category: 'flowchart',
          label: 'Admission Confirmed',
          x: 320,
          y: 970,
          width: 160,
          height: 50,
          fill: '#f1f5f9',
          stroke: '#0f172a',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 9,
        },
        {
          id: 'flow-reject',
          type: 'flow-process',
          category: 'flowchart',
          label: 'Show Capacity Full Error',
          x: 540,
          y: 495,
          width: 170,
          height: 60,
          fill: '#fef2f2',
          stroke: '#dc2626',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 10,
        },
      ],
      edges: [
        {
          id: 'fe-1',
          source: 'flow-start',
          target: 'flow-login',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#334155',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'fe-2',
          source: 'flow-login',
          target: 'flow-check-auth',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#334155',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'fe-3',
          source: 'flow-check-auth',
          target: 'flow-select-event',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          label: 'Yes',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#16a34a',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'fe-4',
          source: 'flow-select-event',
          target: 'flow-seats-available',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#334155',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'fe-5',
          source: 'flow-seats-available',
          target: 'flow-gen-qr',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          label: 'Available',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#16a34a',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'fe-6',
          source: 'flow-seats-available',
          target: 'flow-reject',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Waitlist',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#dc2626',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'fe-7',
          source: 'flow-gen-qr',
          target: 'flow-scan-qr',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          label: 'Present QR',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#334155',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'fe-8',
          source: 'flow-scan-qr',
          target: 'flow-record-db',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          label: 'Scan Success',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#0284c7',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'fe-9',
          source: 'flow-record-db',
          target: 'flow-end',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#16a34a',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
      ],
    },
  },

  // 3. Microservices Cloud Infrastructure with Kafka
  {
    id: 'microservices-kafka',
    name: 'Event-Driven Microservices',
    category: 'software',
    description: 'Decoupled domain services with API Gateway, Kafka Message Broker, and isolated databases.',
    figureNumber: 'Figure 4.1',
    figureCaption: 'Event-Driven Microservices Architecture with Apache Kafka Message Bus',
    preset: 'A4',
    orientation: 'landscape',
    page: {
      id: 'page-microservices',
      name: 'Microservices Topology',
      preset: 'A4',
      orientation: 'landscape',
      width: 1123,
      height: 794,
      background: '#ffffff',
      gridEnabled: true,
      gridSize: 20,
      snapToGrid: true,
      figureNumber: 'Figure 4.1',
      figureCaption: 'Event-Driven Microservices Architecture with Apache Kafka Message Bus',
      captionPosition: 'below',
      nodes: [
        {
          id: 'ms-gw',
          type: 'soft-api',
          category: 'software',
          label: 'Kong API Gateway',
          subLabel: 'Rate Limiting & Auth',
          x: 80,
          y: 280,
          width: 150,
          height: 80,
          fill: '#ffffff',
          stroke: '#d97706',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 1,
        },
        {
          id: 'ms-order',
          type: 'soft-service',
          category: 'software',
          label: 'Order Service',
          subLabel: 'Checkout & Cart Engine',
          x: 320,
          y: 140,
          width: 150,
          height: 75,
          fill: '#ffffff',
          stroke: '#4f46e5',
          strokeWidth: 2,
          strokeStyle: 'solid',
          is3D: true,
          depth3D: 8,
          zIndex: 2,
        },
        {
          id: 'ms-user',
          type: 'soft-service',
          category: 'software',
          label: 'User Service',
          subLabel: 'Profiles & Security',
          x: 320,
          y: 280,
          width: 150,
          height: 75,
          fill: '#ffffff',
          stroke: '#4f46e5',
          strokeWidth: 2,
          strokeStyle: 'solid',
          is3D: true,
          depth3D: 8,
          zIndex: 3,
        },
        {
          id: 'ms-inv',
          type: 'soft-service',
          category: 'software',
          label: 'Inventory Service',
          subLabel: 'Stock & Allocation',
          x: 320,
          y: 420,
          width: 150,
          height: 75,
          fill: '#ffffff',
          stroke: '#4f46e5',
          strokeWidth: 2,
          strokeStyle: 'solid',
          is3D: true,
          depth3D: 8,
          zIndex: 4,
        },
        {
          id: 'ms-kafka',
          type: 'soft-queue',
          category: 'software',
          label: 'Apache Kafka Cluster',
          subLabel: 'order-events · stock-events',
          x: 570,
          y: 240,
          width: 180,
          height: 160,
          fill: '#faf5ff',
          stroke: '#7c3aed',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 5,
        },
        {
          id: 'ms-notify',
          type: 'soft-service',
          category: 'software',
          label: 'Notification Worker',
          subLabel: 'Email & Push Dispatcher',
          x: 840,
          y: 200,
          width: 160,
          height: 75,
          fill: '#ffffff',
          stroke: '#059669',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 6,
        },
        {
          id: 'ms-analytics',
          type: 'soft-service',
          category: 'software',
          label: 'Analytics Consumer',
          subLabel: 'Data Lake Stream Ingest',
          x: 840,
          y: 350,
          width: 160,
          height: 75,
          fill: '#ffffff',
          stroke: '#0284c7',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 7,
        },
      ],
      edges: [
        {
          id: 'me-1',
          source: 'ms-gw',
          target: 'ms-order',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: '/orders',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#4f46e5',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'me-2',
          source: 'ms-gw',
          target: 'ms-user',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: '/users',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#4f46e5',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'me-3',
          source: 'ms-gw',
          target: 'ms-inv',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: '/inventory',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#4f46e5',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'me-4',
          source: 'ms-order',
          target: 'ms-kafka',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Publish OrderCreated',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#7c3aed',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'me-5',
          source: 'ms-inv',
          target: 'ms-kafka',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Publish StockReserved',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#7c3aed',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'me-6',
          source: 'ms-kafka',
          target: 'ms-notify',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Subscribe',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#059669',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'me-7',
          source: 'ms-kafka',
          target: 'ms-analytics',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Subscribe',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#0284c7',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
      ],
    },
  },

  // 4. E-Commerce Database ER Diagram
  {
    id: 'ecommerce-er-diagram',
    name: 'E-Commerce Relational ER Model',
    category: 'database',
    description: 'Structured entity-relationship diagram with primary keys, foreign keys, and cardinalities.',
    figureNumber: 'Figure 5.1',
    figureCaption: 'Entity-Relationship Schema Diagram for the E-Commerce Storefront',
    preset: 'A4',
    orientation: 'landscape',
    page: {
      id: 'page-er-ecommerce',
      name: 'Database ER Diagram',
      preset: 'A4',
      orientation: 'landscape',
      width: 1123,
      height: 794,
      background: '#ffffff',
      gridEnabled: true,
      gridSize: 20,
      snapToGrid: true,
      figureNumber: 'Figure 5.1',
      figureCaption: 'Entity-Relationship Schema Diagram for the E-Commerce Storefront',
      captionPosition: 'below',
      nodes: [
        {
          id: 'er-customer',
          type: 'er-table',
          category: 'database',
          label: 'Customer Table',
          subLabel: 'PK: id · email · password_hash',
          x: 80,
          y: 260,
          width: 180,
          height: 130,
          fill: '#ffffff',
          stroke: '#0f172a',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 1,
        },
        {
          id: 'er-rel-places',
          type: 'er-relationship',
          category: 'database',
          label: 'Places (1 : N)',
          x: 320,
          y: 285,
          width: 130,
          height: 80,
          fill: '#f0f9ff',
          stroke: '#0284c7',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 2,
        },
        {
          id: 'er-order',
          type: 'er-table',
          category: 'database',
          label: 'Order Table',
          subLabel: 'PK: id · FK: customer_id · total_amount',
          x: 510,
          y: 260,
          width: 190,
          height: 130,
          fill: '#ffffff',
          stroke: '#0f172a',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 3,
        },
        {
          id: 'er-item',
          type: 'er-table',
          category: 'database',
          label: 'OrderItem Table',
          subLabel: 'PK: id · FK: order_id · FK: product_id',
          x: 770,
          y: 260,
          width: 190,
          height: 130,
          fill: '#ffffff',
          stroke: '#0f172a',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 4,
        },
        {
          id: 'er-product',
          type: 'er-table',
          category: 'database',
          label: 'Product Catalog',
          subLabel: 'PK: id · sku · name · price_cents',
          x: 770,
          y: 470,
          width: 190,
          height: 130,
          fill: '#ffffff',
          stroke: '#0f172a',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 5,
        },
      ],
      edges: [
        {
          id: 'ere-1',
          source: 'er-customer',
          target: 'er-rel-places',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: '1',
          lineType: 'orthogonal',
          arrowType: 'none',
          stroke: '#334155',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'ere-2',
          source: 'er-rel-places',
          target: 'er-order',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'N',
          lineType: 'orthogonal',
          arrowType: 'none',
          stroke: '#334155',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'ere-3',
          source: 'er-order',
          target: 'er-item',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Contains (1 : N)',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#0284c7',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'ere-4',
          source: 'er-item',
          target: 'er-product',
          sourceHandle: 'bottom',
          targetHandle: 'top',
          label: 'References (N : 1)',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#0284c7',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
      ],
    },
  },

  // 5. Machine Learning Engineering Pipeline
  {
    id: 'ml-pipeline-flow',
    name: 'Machine Learning Engineering Pipeline',
    category: 'software',
    description: 'End-to-end data ingestion, feature store, training, registry, and inference API monitoring.',
    figureNumber: 'Figure 4.3',
    figureCaption: 'Production Machine Learning Lifecycle and Model Serving Pipeline',
    preset: 'A4',
    orientation: 'landscape',
    page: {
      id: 'page-ml-pipeline',
      name: 'ML Pipeline',
      preset: 'A4',
      orientation: 'landscape',
      width: 1123,
      height: 794,
      background: '#ffffff',
      gridEnabled: true,
      gridSize: 20,
      snapToGrid: true,
      figureNumber: 'Figure 4.3',
      figureCaption: 'Production Machine Learning Lifecycle and Model Serving Pipeline',
      captionPosition: 'below',
      nodes: [
        {
          id: 'ml-ingest',
          type: 'soft-storage',
          category: 'software',
          label: 'Raw Data Ingestion',
          subLabel: 'Telemetry & Logs Lake',
          x: 60,
          y: 280,
          width: 150,
          height: 85,
          fill: '#ffffff',
          stroke: '#059669',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 1,
        },
        {
          id: 'ml-clean',
          type: 'soft-service',
          category: 'software',
          label: 'Preprocessing & Clean',
          subLabel: 'Spark / Pandas ETL Job',
          x: 270,
          y: 280,
          width: 160,
          height: 80,
          fill: '#ffffff',
          stroke: '#4f46e5',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 2,
        },
        {
          id: 'ml-features',
          type: 'soft-database',
          category: 'software',
          label: 'Feast Feature Store',
          subLabel: 'Online & Offline Features',
          x: 490,
          y: 275,
          width: 150,
          height: 90,
          fill: '#ffffff',
          stroke: '#0284c7',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 3,
        },
        {
          id: 'ml-train',
          type: 'soft-server',
          category: 'software',
          label: 'GPU Training Cluster',
          subLabel: 'PyTorch Distributed Run',
          x: 700,
          y: 275,
          width: 160,
          height: 90,
          fill: '#ffffff',
          stroke: '#334155',
          strokeWidth: 2,
          strokeStyle: 'solid',
          is3D: true,
          depth3D: 10,
          zIndex: 4,
        },
        {
          id: 'ml-registry',
          type: 'soft-auth',
          category: 'software',
          label: 'MLflow Model Registry',
          subLabel: 'Artifact Versioning & Eval',
          x: 920,
          y: 280,
          width: 160,
          height: 80,
          fill: '#ffffff',
          stroke: '#d97706',
          strokeWidth: 2,
          strokeStyle: 'solid',
          zIndex: 5,
        },
      ],
      edges: [
        {
          id: 'mle-1',
          source: 'ml-ingest',
          target: 'ml-clean',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Parquet Files',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#334155',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'mle-2',
          source: 'ml-clean',
          target: 'ml-features',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Engineered Vectors',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#4f46e5',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'mle-3',
          source: 'ml-features',
          target: 'ml-train',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Training Batches',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#0284c7',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
        {
          id: 'mle-4',
          source: 'ml-train',
          target: 'ml-registry',
          sourceHandle: 'right',
          targetHandle: 'left',
          label: 'Trained Weights',
          lineType: 'orthogonal',
          arrowType: 'arrow',
          stroke: '#d97706',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
        },
      ],
    },
  },
];
