import { ShapeCategory, ShapeDefinition, ShapeType } from '../types/diagram';

export const SHAPE_CATEGORIES: { id: ShapeCategory; name: string }[] = [
  { id: 'basic', name: 'Basic Shapes' },
  { id: 'flowchart', name: 'Flowchart' },
  { id: 'software', name: 'Software Architecture' },
  { id: 'uml', name: 'UML Diagrams' },
  { id: 'database', name: 'Database & ER' },
  { id: 'network', name: 'Network Topology' },
  { id: 'technical-3d', name: '3D Technical Shapes' },
];

export const SHAPE_REGISTRY: Record<ShapeType, ShapeDefinition> = {
  // BASIC
  'rectangle': {
    id: 'rectangle',
    name: 'Rectangle',
    category: 'basic',
    defaultWidth: 150,
    defaultHeight: 80,
    description: 'General purpose rectangular block',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
    is3DSupported: true,
  },
  'rounded-rectangle': {
    id: 'rounded-rectangle',
    name: 'Rounded Rectangle',
    category: 'basic',
    defaultWidth: 150,
    defaultHeight: 80,
    description: 'Smooth cornered container or module',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
    is3DSupported: true,
  },
  'circle': {
    id: 'circle',
    name: 'Circle',
    category: 'basic',
    defaultWidth: 100,
    defaultHeight: 100,
    description: 'Circular node or state',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'ellipse': {
    id: 'ellipse',
    name: 'Ellipse',
    category: 'basic',
    defaultWidth: 140,
    defaultHeight: 90,
    description: 'Elliptical region or concept',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'triangle': {
    id: 'triangle',
    name: 'Triangle',
    category: 'basic',
    defaultWidth: 120,
    defaultHeight: 100,
    description: 'Directional indicator or warning',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'diamond': {
    id: 'diamond',
    name: 'Diamond',
    category: 'basic',
    defaultWidth: 120,
    defaultHeight: 100,
    description: 'Condition or branching node',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'hexagon': {
    id: 'hexagon',
    name: 'Hexagon',
    category: 'basic',
    defaultWidth: 140,
    defaultHeight: 90,
    description: 'Hexagonal cluster or service boundary',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'pentagon': {
    id: 'pentagon',
    name: 'Pentagon',
    category: 'basic',
    defaultWidth: 120,
    defaultHeight: 100,
    description: 'Five-sided step or checkpoint',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'parallelogram': {
    id: 'parallelogram',
    name: 'Parallelogram',
    category: 'basic',
    defaultWidth: 150,
    defaultHeight: 80,
    description: 'Data I/O or tilted section',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'cylinder': {
    id: 'cylinder',
    name: 'Cylinder',
    category: 'basic',
    defaultWidth: 120,
    defaultHeight: 100,
    description: 'Data store or repository',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
    is3DSupported: true,
  },
  'document': {
    id: 'document',
    name: 'Document',
    category: 'basic',
    defaultWidth: 130,
    defaultHeight: 90,
    description: 'Report, file, or printed sheet',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'folder': {
    id: 'folder',
    name: 'Folder',
    category: 'basic',
    defaultWidth: 140,
    defaultHeight: 90,
    description: 'Directory, package, or group archive',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'cloud': {
    id: 'cloud',
    name: 'Cloud',
    category: 'basic',
    defaultWidth: 160,
    defaultHeight: 100,
    description: 'External network or internet service',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },

  // FLOWCHART
  'flow-start-end': {
    id: 'flow-start-end',
    name: 'Start / End',
    category: 'flowchart',
    defaultWidth: 140,
    defaultHeight: 60,
    description: 'Process entry or termination terminal',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#f1f5f9',
    defaultStroke: '#0f172a',
  },
  'flow-process': {
    id: 'flow-process',
    name: 'Process Step',
    category: 'flowchart',
    defaultWidth: 150,
    defaultHeight: 70,
    description: 'Standard operation or transformation',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'flow-decision': {
    id: 'flow-decision',
    name: 'Decision',
    category: 'flowchart',
    defaultWidth: 130,
    defaultHeight: 90,
    description: 'Conditional decision or branch point',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#d97706',
  },
  'flow-input-output': {
    id: 'flow-input-output',
    name: 'Input / Output',
    category: 'flowchart',
    defaultWidth: 150,
    defaultHeight: 70,
    description: 'Data entry or display',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#16a34a',
  },
  'flow-predefined-process': {
    id: 'flow-predefined-process',
    name: 'Predefined Process',
    category: 'flowchart',
    defaultWidth: 160,
    defaultHeight: 75,
    description: 'Subroutine or modular sub-process',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#475569',
  },
  'flow-manual-input': {
    id: 'flow-manual-input',
    name: 'Manual Input',
    category: 'flowchart',
    defaultWidth: 140,
    defaultHeight: 75,
    description: 'Manual data entry by user',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#475569',
  },
  'flow-data': {
    id: 'flow-data',
    name: 'Data Object',
    category: 'flowchart',
    defaultWidth: 140,
    defaultHeight: 75,
    description: 'Stored information or dataset',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0369a1',
  },
  'flow-database': {
    id: 'flow-database',
    name: 'Database Storage',
    category: 'flowchart',
    defaultWidth: 130,
    defaultHeight: 90,
    description: 'Persistent relational or NoSQL database',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'flow-delay': {
    id: 'flow-delay',
    name: 'Delay',
    category: 'flowchart',
    defaultWidth: 130,
    defaultHeight: 70,
    description: 'Scheduled wait or queuing interval',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#64748b',
  },
  'flow-connector': {
    id: 'flow-connector',
    name: 'Off-Page Connector',
    category: 'flowchart',
    defaultWidth: 60,
    defaultHeight: 60,
    description: 'Flow continuation reference',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#f8fafc',
    defaultStroke: '#334155',
  },

  // SOFTWARE ARCHITECTURE
  'soft-user': {
    id: 'soft-user',
    name: 'User / Client',
    category: 'software',
    defaultWidth: 110,
    defaultHeight: 90,
    description: 'End user, consumer, or human operator',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#f8fafc',
    defaultStroke: '#334155',
  },
  'soft-browser': {
    id: 'soft-browser',
    name: 'Web Browser (SPA)',
    category: 'software',
    defaultWidth: 160,
    defaultHeight: 95,
    description: 'Client frontend application in web browser',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'soft-mobile': {
    id: 'soft-mobile',
    name: 'Mobile App',
    category: 'software',
    defaultWidth: 120,
    defaultHeight: 110,
    description: 'iOS or Android native application',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'soft-frontend': {
    id: 'soft-frontend',
    name: 'Frontend Tier',
    category: 'software',
    defaultWidth: 160,
    defaultHeight: 80,
    description: 'User interface presentation layer',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#2563eb',
    is3DSupported: true,
  },
  'soft-backend': {
    id: 'soft-backend',
    name: 'Backend API Service',
    category: 'software',
    defaultWidth: 160,
    defaultHeight: 85,
    description: 'Application server, Node.js, Go, or Python service',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#16a34a',
    is3DSupported: true,
  },
  'soft-api': {
    id: 'soft-api',
    name: 'API Gateway / Endpoint',
    category: 'software',
    defaultWidth: 150,
    defaultHeight: 80,
    description: 'REST, GraphQL, or gRPC gateway',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#d97706',
    is3DSupported: true,
  },
  'soft-server': {
    id: 'soft-server',
    name: 'Server Host',
    category: 'software',
    defaultWidth: 150,
    defaultHeight: 90,
    description: 'Virtual machine or bare metal host',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
    is3DSupported: true,
  },
  'soft-database': {
    id: 'soft-database',
    name: 'Database (SQL/NoSQL)',
    category: 'software',
    defaultWidth: 130,
    defaultHeight: 95,
    description: 'PostgreSQL, MySQL, MongoDB, or DynamoDB',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
    is3DSupported: true,
  },
  'soft-cache': {
    id: 'soft-cache',
    name: 'In-Memory Cache (Redis)',
    category: 'software',
    defaultWidth: 150,
    defaultHeight: 75,
    description: 'Redis or Memcached key-value store',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#dc2626',
    is3DSupported: true,
  },
  'soft-queue': {
    id: 'soft-queue',
    name: 'Message Queue / Bus',
    category: 'software',
    defaultWidth: 160,
    defaultHeight: 75,
    description: 'Kafka, RabbitMQ, or SQS message pipe',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#7c3aed',
    is3DSupported: true,
  },
  'soft-storage': {
    id: 'soft-storage',
    name: 'Object Storage (S3/GCS)',
    category: 'software',
    defaultWidth: 140,
    defaultHeight: 85,
    description: 'Blob or asset file repository',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#059669',
    is3DSupported: true,
  },
  'soft-auth': {
    id: 'soft-auth',
    name: 'Auth / Identity Provider',
    category: 'software',
    defaultWidth: 150,
    defaultHeight: 80,
    description: 'OAuth2, JWT, or SSO authorization service',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#e11d48',
  },
  'soft-cloud': {
    id: 'soft-cloud',
    name: 'Cloud VPC / Region',
    category: 'software',
    defaultWidth: 180,
    defaultHeight: 110,
    description: 'AWS, GCP, Azure, or Cloudflare infrastructure',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#f8fafc',
    defaultStroke: '#0284c7',
  },
  'soft-load-balancer': {
    id: 'soft-load-balancer',
    name: 'Load Balancer',
    category: 'software',
    defaultWidth: 150,
    defaultHeight: 75,
    description: 'Reverse proxy, ALB, or Nginx load distributor',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0d9488',
  },
  'soft-service': {
    id: 'soft-service',
    name: 'Microservice',
    category: 'software',
    defaultWidth: 140,
    defaultHeight: 80,
    description: 'Decoupled domain service component',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#4f46e5',
    is3DSupported: true,
  },

  // UML
  'uml-actor': {
    id: 'uml-actor',
    name: 'Actor',
    category: 'uml',
    defaultWidth: 90,
    defaultHeight: 100,
    description: 'External entity interacting with the system',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#1e293b',
  },
  'uml-use-case': {
    id: 'uml-use-case',
    name: 'Use Case',
    category: 'uml',
    defaultWidth: 150,
    defaultHeight: 75,
    description: 'System capability or interaction sequence',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'uml-class': {
    id: 'uml-class',
    name: 'UML Class',
    category: 'uml',
    defaultWidth: 170,
    defaultHeight: 120,
    description: 'Object-oriented class with attributes & methods',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'uml-interface': {
    id: 'uml-interface',
    name: 'Interface',
    category: 'uml',
    defaultWidth: 160,
    defaultHeight: 90,
    description: 'Type contract specification',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#7c3aed',
  },
  'uml-object': {
    id: 'uml-object',
    name: 'Instance Object',
    category: 'uml',
    defaultWidth: 150,
    defaultHeight: 70,
    description: 'Runtime instantiated class entity',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#475569',
  },
  'uml-component': {
    id: 'uml-component',
    name: 'Component',
    category: 'uml',
    defaultWidth: 160,
    defaultHeight: 85,
    description: 'Modular replaceable system unit',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0d9488',
  },
  'uml-package': {
    id: 'uml-package',
    name: 'Package',
    category: 'uml',
    defaultWidth: 160,
    defaultHeight: 95,
    description: 'Namespace or module grouping container',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#64748b',
  },
  'uml-state': {
    id: 'uml-state',
    name: 'State Node',
    category: 'uml',
    defaultWidth: 140,
    defaultHeight: 65,
    description: 'State machine condition or phase',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'uml-activity': {
    id: 'uml-activity',
    name: 'Activity Action',
    category: 'uml',
    defaultWidth: 150,
    defaultHeight: 65,
    description: 'Activity diagram execution step',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#16a34a',
  },

  // NETWORK
  'net-router': {
    id: 'net-router',
    name: 'Network Router',
    category: 'network',
    defaultWidth: 130,
    defaultHeight: 80,
    description: 'Packet forwarding gateway device',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'net-switch': {
    id: 'net-switch',
    name: 'Network Switch',
    category: 'network',
    defaultWidth: 140,
    defaultHeight: 70,
    description: 'Layer 2/3 local area interconnect',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0d9488',
  },
  'net-firewall': {
    id: 'net-firewall',
    name: 'Firewall (WAF)',
    category: 'network',
    defaultWidth: 140,
    defaultHeight: 80,
    description: 'Security filter and inspection checkpoint',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#dc2626',
  },
  'net-server': {
    id: 'net-server',
    name: 'Server Rack',
    category: 'network',
    defaultWidth: 140,
    defaultHeight: 90,
    description: 'Data center compute node',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },
  'net-desktop': {
    id: 'net-desktop',
    name: 'Workstation / PC',
    category: 'network',
    defaultWidth: 120,
    defaultHeight: 90,
    description: 'Office desktop computer client',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#475569',
  },
  'net-laptop': {
    id: 'net-laptop',
    name: 'Laptop Client',
    category: 'network',
    defaultWidth: 130,
    defaultHeight: 80,
    description: 'Portable end user workstation',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#475569',
  },
  'net-mobile': {
    id: 'net-mobile',
    name: 'Mobile Client',
    category: 'network',
    defaultWidth: 100,
    defaultHeight: 90,
    description: 'Handheld cellular / WiFi client',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#475569',
  },
  'net-internet': {
    id: 'net-internet',
    name: 'Public Internet WAN',
    category: 'network',
    defaultWidth: 160,
    defaultHeight: 95,
    description: 'Global public network backbone',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'net-gateway': {
    id: 'net-gateway',
    name: 'VPN / NAT Gateway',
    category: 'network',
    defaultWidth: 140,
    defaultHeight: 80,
    description: 'Secure tunnel or address translator',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#7c3aed',
  },

  // DATABASE / ER
  'er-entity': {
    id: 'er-entity',
    name: 'Entity',
    category: 'database',
    defaultWidth: 140,
    defaultHeight: 70,
    description: 'Domain entity or data table',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0f172a',
  },
  'er-attribute': {
    id: 'er-attribute',
    name: 'Attribute',
    category: 'database',
    defaultWidth: 120,
    defaultHeight: 60,
    description: 'Entity property or field',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#64748b',
  },
  'er-relationship': {
    id: 'er-relationship',
    name: 'Relationship',
    category: 'database',
    defaultWidth: 130,
    defaultHeight: 80,
    description: 'Associative relationship between entities',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#0284c7',
  },
  'er-table': {
    id: 'er-table',
    name: 'Schema Table (PK/FK)',
    category: 'database',
    defaultWidth: 180,
    defaultHeight: 140,
    description: 'Relational table with columns, keys, and types',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#ffffff',
    defaultStroke: '#334155',
  },

  // 3D TECHNICAL SHAPES (Restrained technical geometry, vector faces)
  '3d-box': {
    id: '3d-box',
    name: '3D Server Block',
    category: 'technical-3d',
    defaultWidth: 160,
    defaultHeight: 90,
    description: 'Extruded isometric technical compute block',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#f8fafc',
    defaultStroke: '#334155',
    is3DSupported: true,
  },
  '3d-cylinder': {
    id: '3d-cylinder',
    name: '3D Database Cylinder',
    category: 'technical-3d',
    defaultWidth: 130,
    defaultHeight: 110,
    description: 'Extruded cylindrical data store with surface shading',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#f8fafc',
    defaultStroke: '#0284c7',
    is3DSupported: true,
  },
  '3d-platform': {
    id: '3d-platform',
    name: '3D Infrastructure Platform',
    category: 'technical-3d',
    defaultWidth: 180,
    defaultHeight: 70,
    description: 'Isometric base platform for layered architectures',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#f1f5f9',
    defaultStroke: '#475569',
    is3DSupported: true,
  },
  '3d-microservice': {
    id: '3d-microservice',
    name: '3D Microservice Cube',
    category: 'technical-3d',
    defaultWidth: 130,
    defaultHeight: 100,
    description: 'Isometric microservice node with port interfaces',
    connectionPoints: ['top', 'right', 'bottom', 'left'],
    defaultFill: '#f8fafc',
    defaultStroke: '#4f46e5',
    is3DSupported: true,
  },
};
